--[[
   Copyright © 2025 Davi PEIXELAS
   Licensed under the MIT License.
   See LICENSE file in the project root for full license text.
   
   GTA-SA
    built and generated by: HG, PEIXE 
    Creator of the title and image: KillerSA
     | AIM FOR THE CAM |
   https://discord.gg/N49fmtT3VZ   -community
--]]
script_author ("HG", "PEIXE", "CRIADOR DO TÍTULO E IMAGEM: KillerSA") -- 👍🏼
script_name "AimForTheCâmera"
script_version "Monetloader 3.6.0-Os"

local memory = require("memory")

function main()
    memory.setfloat(MONET_GTASA_BASE+ 0x3C6D50, 1, true)
    while true do
        wait(0)
    end
end
